# Generated by Django 3.0.6 on 2020-05-29 01:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20200529_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
