# Generated by Django 3.0.6 on 2020-05-31 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course_abs_to_mti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
