# Generated by Django 3.0.6 on 2020-05-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_courseold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['start'], 'verbose_name': 'palestra', 'verbose_name_plural': 'palestras'},
        ),
    ]
